In [311]:
import numpy as np

# Question 1
# Write a function that creates a 2D NumPy array with 5 rows and 3 columns
# where each element is the sum of its row and column indices.
def q1():
    xs = np.arange(3)
    ys = np.arange(5)
    x, y = np.meshgrid(xs, ys)
    return x + y

# Example usage:
# result = q1()
# Expected output: A 5x3 NumPy array where the value at position [i,j] equals i+j


# Question 2
# Write a function that takes a 1D NumPy array and returns a new array containing
# all elements that are greater than the mean of the array.
def q2(arr):
    return arr[arr > arr.mean()]

# Example usage:
# input_array = np.array([1, 3, 5, 7, 9])
# result = q2(input_array)
# Expected output: array([7, 9])


# Question 3
# Implement a function that performs element-wise multiplication of two arrays with broadcasting.
# Your function should take a 1D array of shape (n,) and a 2D array of shape (m,n)
# and return a 2D array of shape (m,n).
def q3(a, b):
    return a * b

# Example usage:
# a = np.array([1, 2, 3])
# b = np.array([[4, 5, 6], [7, 8, 9]])
# result = q3(a, b)
# Expected output: array([[ 4, 10, 18], [ 7, 16, 27]])


# Question 4
# Write a function that computes the moving average of a 1D array over a specified window size.
# The output array should have the same length as the input array,
# with NaN values at the beginning where the full window isn't available.
def q4(arr, window_size):
    cum_sum = arr.cumsum()
    deduct_sum = cum_sum[:-window_size] 
    non_sum = np.repeat(0, window_size)
    deduction = np.concatenate((non_sum, deduct_sum))
    roll_mean = (cum_sum - deduction)/window_size
    result = np.where(np.array(range(len(roll_mean)))<window_size-1, np.nan, roll_mean)
    return result

# Example usage:
# arr = np.array([1, 2, 3, 4, 5])
# window_size = 3
# result = q4(arr, window_size)
# Expected output: array([nan, nan, 2., 3., 4.])


# Question 5
# Create a function that takes a 2D array and returns the row indices sorted
# by the sum of elements in each row, from smallest to largest.
def q5(arr):
    row_sums = arr.sum(axis = 1)
    row_order = row_sums.argsort()
    return row_order

# Example usage:
# input_array = np.array([[5, 2], [1, 3], [7, 0]])
# result = q5(input_array)
# Expected output: array([1, 0, 2])


# Question 6
# Write a function that takes a 1D NumPy array and creates a histogram with 5 bins,
# returning the bin counts as a NumPy array.
def q6(arr):
    hist, _ = np.histogram(arr, bins = 5)
    return hist

# Example usage:
# input_array = np.array([1, 8, 3, 7, 2, 5, 10, 4, 9, 6])
# result = q6(input_array)
# Expected output: array([3, 2, 2, 2, 1])


# Question 7
# Implement a function that takes two 2D arrays and returns True if they can
# be matrix-multiplied, and False otherwise.
def q7(a, b):
    # Your code here
    pass

# Example usage:
# a = np.random.rand(3, 4)
# b = np.random.rand(4, 5)
# result = q7(a, b)
# Expected output: True


# Question 8
# Write a function that creates a random 4x4 matrix and returns its inverse.
# If the matrix is not invertible (determinant is zero), return None.
def q8():
    rand_seed = np.random.default_rng(1)
    mat = rand_seed.integers(-5, 6, 16).reshape(4,4)
    return mat.T

# Example usage:
# result = q8()
# Expected output: A 4x4 NumPy array (inverse of the random matrix) or None


# Question 9
# Create a function that takes a 1D array of strings and performs vectorized string operations to:
# 1) convert all strings to uppercase, 2) remove any spaces, and 3) return the length of each resulting string.
def q9(arr):
    # Import the char module if needed
    import numpy as np
    
    # 1) Convert all strings to uppercase
    uppercase_arr = np.char.upper(arr)
    
    # 2) Remove any spaces
    no_spaces_arr = np.char.replace(uppercase_arr, ' ', '')
    
    # 3) Return the length of each resulting string
    lengths = np.char.str_len(no_spaces_arr)
    
    return lengths

# Example usage:
# input_array = np.array(['hello world', 'numpy', 'python data'])
# result = q9(input_array)
# Expected output: array([10, 5, 11])


# Question 10
# Write a function that applies a custom universal function to each element in a 3x3 array.
# The function should replace:
# - Values less than 0 with -1
# - Values between 0 and 1 (inclusive) with 0
# - Values greater than 1 with 1
def q10(arr):
    conditions = [input_array < 0, (input_array > 0) & (input_array <= 1), input_array > 1]
    output = np.select(conditions, [-1, 0, 1])
    return output

# Example usage:
# input_array = np.array([[-0.5, 0, 0.5], [1, 1.5, -1], [0.25, -2, 2]])
# result = q10(input_array)
# Expected output: array([[-1,  0,  0], [ 0,  1, -1], [ 0, -1,  1]])


# Test your solutions
if __name__ == "__main__":
    # Test Question 1
    result1 = q1()
    print("Q1 Result:\n", result1)
    
    # Test Question 2
    test2 = np.array([1, 3, 5, 7, 9])
    result2 = q2(test2)
    print("Q2 Result:", result2)
    
    # Test Question 3
    a3 = np.array([1, 2, 3])
    b3 = np.array([[4, 5, 6], [7, 8, 9]])
    result3 = q3(a3, b3)
    print("Q3 Result:\n", result3)
    
    # Test Question 4
    arr4 = np.array([1, 2, 3, 4, 5])
    result4 = q4(arr4, 3)
    print("Q4 Result:", result4)
    
    # Test Question 5
    test5 = np.array([[5, 2], [1, 3], [7, 0]])
    result5 = q5(test5)
    print("Q5 Result:", result5)
    
    # Test Question 6
    test6 = np.array([1, 8, 3, 7, 2, 5, 10, 4, 9, 6])
    result6 = q6(test6)
    print("Q6 Result:", result6)
    
    # Test Question 7
    a7 = np.random.rand(3, 4)
    b7 = np.random.rand(4, 5)
    result7 = q7(a7, b7)
    print("Q7 Result:", result7)
    
    # Test Question 8
    result8 = q8()
    print("Q8 Result:\n", result8)
    
    # Test Question 9
    test9 = np.array(['hello world', 'numpy', 'python data'])
    result9 = q9(test9)
    print("Q9 Result:", result9)
    
    # Test Question 10
    test10 = np.array([[-0.5, 0, 0.5], [1, 1.5, -1], [0.25, -2, 2]])
    result10 = q10(test10)
    print("Q10 Result:\n", result10)

Q1 Result:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
Q2 Result: [7 9]
Q3 Result:
 [[ 4 10 18]
 [ 7 16 27]]
Q4 Result: [nan nan  2.  3.  4.]
Q5 Result: [1 0 2]
Q6 Result: [2 2 2 2 2]
Q7 Result: None
Q8 Result:
 [[ 0 -5 -3 -2]
 [ 0 -4 -2  4]
 [ 3  4  4 -3]
 [ 5  5 -1 -1]]
Q9 Result: [10  5 10]


UFuncTypeError: ufunc 'less' did not contain a loop with signature matching types (<class 'numpy.dtypes.StrDType'>, <class 'numpy.dtypes._PyLongDType'>) -> None